# Configuración de Base de Datos
db.url=jdbc:mysql://localhost:3306/parqueadero_autos_colombia
db.user=root
db.password=Juneam25
db.driver=com.mysql.cj.jdbc.Driver

# Configuración de la aplicación
app.nombre=Parqueadero Autos Colombia
app.version=1.0